name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - name: Create virtualenv
        run: python -m venv .venv
      - name: Install dependencies
        run: .venv/bin/pip install .[dev]
      - name: Build crate
        run: .venv/bin/maturin develop
      - name: Verify ruff format
        run: .venv/bin/ruff format --check .
      - name: Verify ruff check
        run: .venv/bin/ruff check .
      - name: Verify cargo fmt
        run: cargo fmt --check
      - name: Run tests
        run: .venv/bin/pytest -vv
